name: format code with prettier

on:
  push:
    branches:
      - '**'  # Déclenche l'action sur chaque commit dans n'importe quelle branche
      -
permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'  # ou une autre version de Node.js compatible

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier to format code
        run: npx prettier --write "**/*.ts"

      - name: Commit and push changes
        run: |
          git config --global user.name 'code-formatter[bot]'
          git config --global user.email 'code-formatter[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto format code with Prettier" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
